-- 1. Crear tabla de configuraciones (Settings)
create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

-- Insertar configuraciones por defecto
insert into public.settings (key, value) values
  ('nombreGym', '"Mi Gimnasio"'),
  ('precioMensual', '0'),
  ('tasaManual', '0'),
  ('mensajeWhatsApp', '"Hola {nombre}! 👋 Te recordamos que tu mensualidad en {gym} vence el {fecha}. ¡Te esperamos para renovar! 💪🏋️"')
on conflict (key) do nothing;

-- 2. Crear tabla de miembros (Members)
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellido text not null,
  cedula text unique,
  edad integer not null,
  telefono text not null,
  correo text,
  "fechaInscripcion" timestamp with time zone default now() not null,
  estado text not null default 'activo',
  notas text default '',
  "createdAt" timestamp with time zone default now() not null
);

-- 3. Crear tabla de pagos (Payments)
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  "memberId" bigint references public.members(id) on delete cascade not null,
  "montoBs" numeric not null,
  "tasaUsd" numeric not null,
  "montoUsd" numeric not null,
  "fechaPago" timestamp with time zone not null,
  "fechaVencimiento" timestamp with time zone not null,
  "diasPlan" integer not null default 30,
  "metodoPago" text not null,
  banco text,
  referencia text,
  concepto text not null default 'mensualidad',
  notas text default '',
  "createdAt" timestamp with time zone default now() not null
);

-- 4. Habilitar Seguridad de Nivel de Fila (RLS) pero permitir acceso anónimo 
-- (Como es una app local sin login, permitimos lectura y escritura a cualquiera con la Anon Key)
alter table public.settings enable row level security;
alter table public.members enable row level security;
alter table public.payments enable row level security;

create policy "Permitir acceso anonimo a settings" on public.settings for all using (true) with check (true);
create policy "Permitir acceso anonimo a members" on public.members for all using (true) with check (true);
create policy "Permitir acceso anonimo a payments" on public.payments for all using (true) with check (true);
